<a href="https://colab.research.google.com/github/MorojMunshi/Data-Analysis-2/blob/main/Lab_1_Exploring_LSTM_and_GRU_Architectures_in_Sequence_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction:
In this lab, you will explore the Long Short-Term Memory (LSTM) and Gated Recurrent Unit (GRU) architectures—two advanced recurrent neural network (RNN) models designed to handle sequential data effectively.

The main objectives of today lab are as follow:

1. Train and test LSTM and GRU models on three types of sequence modeling tasks:

    * One-to-Many: Sequence generation from a single input.
    * Many-to-One: Classifying a sequence based on its pattern.
    * Many-to-Many: Translating one sequence into another.

2. Test the performance of these models.
3. Compare the results of LSTM and GRU for each task.

#Task one: One-to-Many

First, Synthetic datasets are used to simplify implementation and focus on learning model mechanics.

The task is to Generate a sequence of integers starting from a single input integer. So, our trining data is an inte

In [1]:
import numpy as np

# Generate dataset
def generate_one_to_many_data(size=1000):
    X = np.random.randint(1, 100, size=(size, 1))  # Single numbers
    y = np.array([np.arange(x, x + 5) for x in X.flatten()])  # Sequence of 5 numbers
    return X, y

X, y = generate_one_to_many_data()

print the first 10 rows from X and y, so u undersand how it looks like.

In [4]:
# the # Print the first 10 rows of X and y

print("First 10 inputs (X):")

print(X[:10])

First 10 inputs (X):
[[93]
 [69]
 [63]
 [86]
 [66]
 [61]
 [78]
 [29]
 [76]
 [19]]


array([[76, 77, 78, 79, 80],
       [26, 27, 28, 29, 30],
       [ 7,  8,  9, 10, 11],
       [90, 91, 92, 93, 94],
       [77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86],
       [46, 47, 48, 49, 50],
       [ 9, 10, 11, 12, 13],
       [ 1,  2,  3,  4,  5]])

###Model Implementation and Training:
Implement and train two sequence modeling architectures: LSTM (Long Short-Term Memory) and GRU (Gated Recurrent Unit). follow these steps:

1. __Build the Models:__ Define LSTM and GRU models using the Keras library,specifying the number of neurons, input shapes, and layers. (Hint: Use the Sequential API in Keras to stack layers. Start with an LSTM or GRU layer, followed by a dense layer to generate the output sequence.)

2. __Compile the Models:__ Choose appropriate loss functions and optimizers to train the models efficiently. (Hint: Since our data consists of numerical values, use mean squared error (MSE) as the loss function for regression tasks. Use an optimizer like Adam for faster convergence.)

3. __Train the Models:__ Use the training dataset to adjust model weights through backpropagation, minimizing the loss over multiple epochs. Do not forget to add a validation set during training to monitor for overfitting and fine-tune the model.
(Hint: Ensure the input data is correctly shaped to match the expected input dimensions of the LSTM or GRU (samples, timesteps, features). Use a batch size that balances speed and memory usage (e.g., 32).)

In [ ]:
# Reshape input for LSTM/GRU
X = X.reshape(-1, 1, 1)  # (samples, timesteps, features)
y = y.reshape(-1, 5)  # (samples, timesteps)

###Test the model

Test both of your models on a single input of 10 and predict the output sequence. Verify if the output matches the expected sequence (10, 11, 12, 13, 14). Note that your model will produce floating-point numbers; to quickly convert them to integers, you can use the np.round function.

In [ ]:
test_input = np.array([10]).reshape(-1, 1, 1)  # Test input

###Improve model performance
If your model does not perform well on the test data, try one of the following strategies to improve its performance:

* Increase Training Epochs: Train the model for more epochs to allow it to better learn the patterns in the data.
* Increase Model Complexity: Add more neurons or additional layers to enhance the model's capacity to capture complex relationships.
* Adjust the Learning Rate: If the loss is fluctuating or convergence is slow, use a learning rate scheduler or manually modify the optimizer's learning rate.

#Task Two: Many-to-One Task – Sequence Classification
The task is to Classify sequences as increasing (1) or decreasing (0).

*Dataset* Preparation:

In [ ]:
import numpy as np
from sklearn.utils import shuffle

# Generate training dataset
def generate_many_to_one_data(size, seq_length=5):
    # Half of the dataset will have increasing sequences (label = 1)
    # Half of the dataset will have decreasing sequences (label = 0)
    X2 = np.zeros((size, seq_length))
    y2 = np.zeros(size)

    for i in range(size // 2):
        # Generate increasing sequence (label = 1)
        X2[i] = np.arange(i+1, i + seq_length + 1)
        y2[i] = 1  # Increasing sequence

        # Generate decreasing sequence (label = 0)
        X2[size // 2 + i] = np.arange(i + seq_length, i, -1)
        y2[size // 2 + i] = 0  # Decreasing sequence

    return X2, y2

# Generate a balanced dataset
X2, y2 = generate_many_to_one_data(1000)

# Shuffle the dataset
X2, y2 = shuffle(X2, y2, random_state=42)

# Reshape input for LSTM/GRU
X2 = X2.reshape(-1, 5, 1)

###Model Implementation and Training:
Implement and train two sequence modeling architectures: LSTM (Long Short-Term Memory) and GRU (Gated Recurrent Unit). follow the same steps as you did in task 1


###Test the model

In [ ]:
# Generate a balanced dataset
X2_test, y2_test = generate_many_to_one_data(10)

# Reshape input for LSTM/GRU
X2_test = X2_test.reshape(-1, 5, 1)

###Improve model performance
if your model does not produce the true labels, try to improve it using the techniques you applied in Task 1.

# Task Three: Many-to-Many Task – Sequence Translation
The task is to Translate a sequence of numbers into their squares.

Dataset Preparation:

In [ ]:
# Generate dataset with sequential input and corresponding squared outputs
def generate_sequential_many_to_many_data(size, seq_length=5):
    X3 = np.zeros((size, seq_length))  # Initialize input array
    for i in range(size):
        start = np.random.randint(1, 50)  # Random starting point
        X3[i] = np.arange(start, start + seq_length)  # Generate sequential numbers
    y3 = X3**2  # Output is the square of the input sequence
    return X3, y3

X3, y3 = generate_sequential_many_to_many_data(1000)

# Reshape input for LSTM/GRU
X3 = X3.reshape(-1, 5, 1)
y3 = y3.reshape(-1, 5, 1)

Print the first few examples

Example input (X3): [[[22.]
  [23.]
  [24.]
  [25.]
  [26.]]

 [[30.]
  [31.]
  [32.]
  [33.]
  [34.]]

 [[13.]
  [14.]
  [15.]
  [16.]
  [17.]]]
Example output (y3): [[[ 484.]
  [ 529.]
  [ 576.]
  [ 625.]
  [ 676.]]

 [[ 900.]
  [ 961.]
  [1024.]
  [1089.]
  [1156.]]

 [[ 169.]
  [ 196.]
  [ 225.]
  [ 256.]
  [ 289.]]]


###Model Implementation and Training:
Implement and train two sequence modeling architectures: LSTM (Long Short-Term Memory) and GRU (Gated Recurrent Unit). follow the same steps as you did in task 1


###Test the model
Test both of your models using one sequence starting at 2 and predict the output sequence. Verify if the output matches the expected sequence (4,  9, 16, 25, 36).

In [ ]:
# Example test input
X3_test = np.array([[2, 3, 4, 5, 6]])  # A sequence starting at 2
X3_test = test_input.reshape(1, 5, 1)  # Reshape to match model input shape

###Improve model performance
If your model does not produce the true labels, try to improve it using the techniques you applied in Task 1.

Good luck!


#**Question:**
Briefly summarize what you did in this lab. For each task, discuss which model performed better and why. (Note: Write in your own words in Arabic)